services:
  web:
    build: .
    container_name: api
    ports:
      - "${HOST_PORT}:80"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5433/${POSTGRES_DB}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app_src

  db:
    image: postgres:alpine
    container_name: postgres_db
    ports:
      - "${HOST_POSTGRES_PORT}:5433"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env
volumes:
  postgres_data:
    driver: local